import typing

import numpy

TrackbarCallback = typing.Callable[[int], None]

def createTrackbar(
    trackbarname: str, winname: str, value: int, count: int, onChange: TrackbarCallback
) -> int: ...
def getTrackbarPos(trackbarname: str, winname: str) -> int: ...
def imshow(winname: str, mat: numpy.ndarray) -> None: ...
def namedWindow(winname: str) -> None: ...
def setTrackbarMin(trackbarname: str, winname: str, minval: int) -> None: ...
def setTrackbarPos(trackbarname: str, winname: str, pos: int) -> None: ...
def waitKey(delay: int = ...) -> int: ...
